/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AccessibilityRouteImport } from './routes/accessibility'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as CareersRouteImport } from './routes/careers'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CookiesRouteImport } from './routes/cookies'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as DoctorDashboardRouteImport } from './routes/doctor-dashboard'
import { Route as DoctorPortalRouteImport } from './routes/doctor-portal'
import { Route as DoctorsRouteImport } from './routes/doctors'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as FindADoctorRouteImport } from './routes/find-a-doctor'
import { Route as FitnessRouteImport } from './routes/fitness'
import { Route as HealthRouteImport } from './routes/health'
import { Route as HealthRecordsRouteImport } from './routes/health-records'
import { Route as HelpRouteImport } from './routes/help'
import { Route as JoinRouteImport } from './routes/join'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MedicationsRouteImport } from './routes/medications'
import { Route as NotificationsRouteImport } from './routes/notifications'
import { Route as NutritionRouteImport } from './routes/nutrition'
import { Route as PlatformRouteImport } from './routes/platform'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as PrivacyRouteImport } from './routes/privacy'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as TermsRouteImport } from './routes/terms'
import { Route as AuthConfirmRouteImport } from './routes/auth.confirm'
import { Route as BookDoctorIdRouteImport } from './routes/book.$doctorId'
import { Route as DoctorsDoctorIdRouteImport } from './routes/doctors_.$doctorId'
import { Route as AppointmentsConfirmTokenRouteImport } from './routes/appointments_.confirm.$token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AccessibilityRoute = AccessibilityRouteImport.update({
  id: '/accessibility',
  path: '/accessibility',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const CareersRoute = CareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CookiesRoute = CookiesRouteImport.update({
  id: '/cookies',
  path: '/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorDashboardRoute = DoctorDashboardRouteImport.update({
  id: '/doctor-dashboard',
  path: '/doctor-dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorPortalRoute = DoctorPortalRouteImport.update({
  id: '/doctor-portal',
  path: '/doctor-portal',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsRoute = DoctorsRouteImport.update({
  id: '/doctors',
  path: '/doctors',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const FindADoctorRoute = FindADoctorRouteImport.update({
  id: '/find-a-doctor',
  path: '/find-a-doctor',
  getParentRoute: () => rootRouteImport,
} as any)
const FitnessRoute = FitnessRouteImport.update({
  id: '/fitness',
  path: '/fitness',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRoute = HealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => rootRouteImport,
} as any)
const HealthRecordsRoute = HealthRecordsRouteImport.update({
  id: '/health-records',
  path: '/health-records',
  getParentRoute: () => rootRouteImport,
} as any)
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinRoute = JoinRouteImport.update({
  id: '/join',
  path: '/join',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MedicationsRoute = MedicationsRouteImport.update({
  id: '/medications',
  path: '/medications',
  getParentRoute: () => rootRouteImport,
} as any)
const NotificationsRoute = NotificationsRouteImport.update({
  id: '/notifications',
  path: '/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const NutritionRoute = NutritionRouteImport.update({
  id: '/nutrition',
  path: '/nutrition',
  getParentRoute: () => rootRouteImport,
} as any)
const PlatformRoute = PlatformRouteImport.update({
  id: '/platform',
  path: '/platform',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacyRoute = PrivacyRouteImport.update({
  id: '/privacy',
  path: '/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const TermsRoute = TermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const BookDoctorIdRoute = BookDoctorIdRouteImport.update({
  id: '/book/$doctorId',
  path: '/book/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const DoctorsDoctorIdRoute = DoctorsDoctorIdRouteImport.update({
  id: '/doctors_/$doctorId',
  path: '/doctors/$doctorId',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsConfirmTokenRoute =
  AppointmentsConfirmTokenRouteImport.update({
    id: '/appointments_/confirm/$token',
    path: '/appointments/confirm/$token',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/fitness': typeof FitnessRoute
  '/health': typeof HealthRoute
  '/health-records': typeof HealthRecordsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/appointments/confirm/$token': typeof AppointmentsConfirmTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/fitness': typeof FitnessRoute
  '/health': typeof HealthRoute
  '/health-records': typeof HealthRecordsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors/$doctorId': typeof DoctorsDoctorIdRoute
  '/appointments/confirm/$token': typeof AppointmentsConfirmTokenRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/accessibility': typeof AccessibilityRoute
  '/appointments': typeof AppointmentsRoute
  '/careers': typeof CareersRoute
  '/contact': typeof ContactRoute
  '/cookies': typeof CookiesRoute
  '/dashboard': typeof DashboardRoute
  '/doctor-dashboard': typeof DoctorDashboardRoute
  '/doctor-portal': typeof DoctorPortalRoute
  '/doctors': typeof DoctorsRoute
  '/faq': typeof FaqRoute
  '/find-a-doctor': typeof FindADoctorRoute
  '/fitness': typeof FitnessRoute
  '/health': typeof HealthRoute
  '/health-records': typeof HealthRecordsRoute
  '/help': typeof HelpRoute
  '/join': typeof JoinRoute
  '/login': typeof LoginRoute
  '/medications': typeof MedicationsRoute
  '/notifications': typeof NotificationsRoute
  '/nutrition': typeof NutritionRoute
  '/platform': typeof PlatformRoute
  '/pricing': typeof PricingRoute
  '/privacy': typeof PrivacyRoute
  '/resources': typeof ResourcesRoute
  '/settings': typeof SettingsRoute
  '/signup': typeof SignupRoute
  '/terms': typeof TermsRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/book/$doctorId': typeof BookDoctorIdRoute
  '/doctors_/$doctorId': typeof DoctorsDoctorIdRoute
  '/appointments_/confirm/$token': typeof AppointmentsConfirmTokenRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/doctor-dashboard'
    | '/doctor-portal'
    | '/doctors'
    | '/faq'
    | '/find-a-doctor'
    | '/fitness'
    | '/health'
    | '/health-records'
    | '/help'
    | '/join'
    | '/login'
    | '/medications'
    | '/notifications'
    | '/nutrition'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/confirm'
    | '/book/$doctorId'
    | '/doctors/$doctorId'
    | '/appointments/confirm/$token'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/doctor-dashboard'
    | '/doctor-portal'
    | '/doctors'
    | '/faq'
    | '/find-a-doctor'
    | '/fitness'
    | '/health'
    | '/health-records'
    | '/help'
    | '/join'
    | '/login'
    | '/medications'
    | '/notifications'
    | '/nutrition'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/confirm'
    | '/book/$doctorId'
    | '/doctors/$doctorId'
    | '/appointments/confirm/$token'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/accessibility'
    | '/appointments'
    | '/careers'
    | '/contact'
    | '/cookies'
    | '/dashboard'
    | '/doctor-dashboard'
    | '/doctor-portal'
    | '/doctors'
    | '/faq'
    | '/find-a-doctor'
    | '/fitness'
    | '/health'
    | '/health-records'
    | '/help'
    | '/join'
    | '/login'
    | '/medications'
    | '/notifications'
    | '/nutrition'
    | '/platform'
    | '/pricing'
    | '/privacy'
    | '/resources'
    | '/settings'
    | '/signup'
    | '/terms'
    | '/auth/confirm'
    | '/book/$doctorId'
    | '/doctors_/$doctorId'
    | '/appointments_/confirm/$token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AccessibilityRoute: typeof AccessibilityRoute
  AppointmentsRoute: typeof AppointmentsRoute
  CareersRoute: typeof CareersRoute
  ContactRoute: typeof ContactRoute
  CookiesRoute: typeof CookiesRoute
  DashboardRoute: typeof DashboardRoute
  DoctorDashboardRoute: typeof DoctorDashboardRoute
  DoctorPortalRoute: typeof DoctorPortalRoute
  DoctorsRoute: typeof DoctorsRoute
  FaqRoute: typeof FaqRoute
  FindADoctorRoute: typeof FindADoctorRoute
  FitnessRoute: typeof FitnessRoute
  HealthRoute: typeof HealthRoute
  HealthRecordsRoute: typeof HealthRecordsRoute
  HelpRoute: typeof HelpRoute
  JoinRoute: typeof JoinRoute
  LoginRoute: typeof LoginRoute
  MedicationsRoute: typeof MedicationsRoute
  NotificationsRoute: typeof NotificationsRoute
  NutritionRoute: typeof NutritionRoute
  PlatformRoute: typeof PlatformRoute
  PricingRoute: typeof PricingRoute
  PrivacyRoute: typeof PrivacyRoute
  ResourcesRoute: typeof ResourcesRoute
  SettingsRoute: typeof SettingsRoute
  SignupRoute: typeof SignupRoute
  TermsRoute: typeof TermsRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
  BookDoctorIdRoute: typeof BookDoctorIdRoute
  DoctorsDoctorIdRoute: typeof DoctorsDoctorIdRoute
  AppointmentsConfirmTokenRoute: typeof AppointmentsConfirmTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accessibility': {
      id: '/accessibility'
      path: '/accessibility'
      fullPath: '/accessibility'
      preLoaderRoute: typeof AccessibilityRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/careers': {
      id: '/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof CareersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cookies': {
      id: '/cookies'
      path: '/cookies'
      fullPath: '/cookies'
      preLoaderRoute: typeof CookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-dashboard': {
      id: '/doctor-dashboard'
      path: '/doctor-dashboard'
      fullPath: '/doctor-dashboard'
      preLoaderRoute: typeof DoctorDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctor-portal': {
      id: '/doctor-portal'
      path: '/doctor-portal'
      fullPath: '/doctor-portal'
      preLoaderRoute: typeof DoctorPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors': {
      id: '/doctors'
      path: '/doctors'
      fullPath: '/doctors'
      preLoaderRoute: typeof DoctorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/find-a-doctor': {
      id: '/find-a-doctor'
      path: '/find-a-doctor'
      fullPath: '/find-a-doctor'
      preLoaderRoute: typeof FindADoctorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/fitness': {
      id: '/fitness'
      path: '/fitness'
      fullPath: '/fitness'
      preLoaderRoute: typeof FitnessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health': {
      id: '/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof HealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/health-records': {
      id: '/health-records'
      path: '/health-records'
      fullPath: '/health-records'
      preLoaderRoute: typeof HealthRecordsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join': {
      id: '/join'
      path: '/join'
      fullPath: '/join'
      preLoaderRoute: typeof JoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/medications': {
      id: '/medications'
      path: '/medications'
      fullPath: '/medications'
      preLoaderRoute: typeof MedicationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/notifications': {
      id: '/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof NotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nutrition': {
      id: '/nutrition'
      path: '/nutrition'
      fullPath: '/nutrition'
      preLoaderRoute: typeof NutritionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/platform': {
      id: '/platform'
      path: '/platform'
      fullPath: '/platform'
      preLoaderRoute: typeof PlatformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacy': {
      id: '/privacy'
      path: '/privacy'
      fullPath: '/privacy'
      preLoaderRoute: typeof PrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/terms': {
      id: '/terms'
      path: '/terms'
      fullPath: '/terms'
      preLoaderRoute: typeof TermsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book/$doctorId': {
      id: '/book/$doctorId'
      path: '/book/$doctorId'
      fullPath: '/book/$doctorId'
      preLoaderRoute: typeof BookDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/doctors_/$doctorId': {
      id: '/doctors_/$doctorId'
      path: '/doctors/$doctorId'
      fullPath: '/doctors/$doctorId'
      preLoaderRoute: typeof DoctorsDoctorIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments_/confirm/$token': {
      id: '/appointments_/confirm/$token'
      path: '/appointments/confirm/$token'
      fullPath: '/appointments/confirm/$token'
      preLoaderRoute: typeof AppointmentsConfirmTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AccessibilityRoute: AccessibilityRoute,
  AppointmentsRoute: AppointmentsRoute,
  CareersRoute: CareersRoute,
  ContactRoute: ContactRoute,
  CookiesRoute: CookiesRoute,
  DashboardRoute: DashboardRoute,
  DoctorDashboardRoute: DoctorDashboardRoute,
  DoctorPortalRoute: DoctorPortalRoute,
  DoctorsRoute: DoctorsRoute,
  FaqRoute: FaqRoute,
  FindADoctorRoute: FindADoctorRoute,
  FitnessRoute: FitnessRoute,
  HealthRoute: HealthRoute,
  HealthRecordsRoute: HealthRecordsRoute,
  HelpRoute: HelpRoute,
  JoinRoute: JoinRoute,
  LoginRoute: LoginRoute,
  MedicationsRoute: MedicationsRoute,
  NotificationsRoute: NotificationsRoute,
  NutritionRoute: NutritionRoute,
  PlatformRoute: PlatformRoute,
  PricingRoute: PricingRoute,
  PrivacyRoute: PrivacyRoute,
  ResourcesRoute: ResourcesRoute,
  SettingsRoute: SettingsRoute,
  SignupRoute: SignupRoute,
  TermsRoute: TermsRoute,
  AuthConfirmRoute: AuthConfirmRoute,
  BookDoctorIdRoute: BookDoctorIdRoute,
  DoctorsDoctorIdRoute: DoctorsDoctorIdRoute,
  AppointmentsConfirmTokenRoute: AppointmentsConfirmTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
